filter_by_attributes.py:
  working_directory: C:/Users/gwena/Documents/STDL/2_En_cours/occupation-toitures/02_Data
  input_files:
    roofs: initial\vector\SHP_CAD_BATIMENT_HORSOL_TOIT\CAD_BATIMENT_HORSOL_TOIT.shp
    potential_solar_surfaces: initial\vector\SHP_OCEN_SOLAIRE_ID_SURFACE_BASE\OCEN_SOLAIRE_ID_SURFACE_BASE.shp
    heritage:
      ensembles: initial\vector\SHP_DPS_ENSEMBLE\DPS_ENSEMBLE.shp
      classement: initial\vector\SHP_DPS_CLASSEMENT\DPS_CLASSEMENT.shp
    industrial_zones: initial\vector\SHP_FTI_PERIMETRE\FTI_PERIMETRE.shp
  parameters:
    solar_absolute_minimum_area: 2  # The script should be adapted for it to be the absolute minimum area
    house_vs_building: xx   # Distinction not applicable yet -> what the difference? We do not currently have the buildings high
    houses:
      flat_vs_pitched: 20   # angle limit in degree
      flat_roofs:
        solar_area: 25      # surface limit in m2
      pitched_roofs:
        solar_area: 15      # surface limit in m2
    buildings:
      solar_area: 200       # surface limit in m2
    industrial_buildings:
      flat_vs_pitched: 20   # angle limit in degree
      flat_roofs:
        solar_area: 200      # surface limit in m2
      pitched_roofs:
        solar_area: 150      # surface limit in m2
    vegetation_area: 20     # surface limit in m2
    vegetation_inclination: 15    # 5% = 2.86Â° -> set to 15, because we have the average slope and it is very sensitive to obstacles